version: "3.8"
services:
  backend:
    build: ./backend
    container_name: cloud-blog-backend
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - COSMOS_URI=${COSMOS_URI}
      - COSMOS_KEY=${COSMOS_KEY}
      - PORT=5000
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: cloud-blog-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: unless-stopped
